#!/bin/bash
# Douyin Archiving Setup Script
# Generated by CEO Agent - Phase 1.5 Archiving Specialist

set -e  # Exit on error

echo "================================================"
echo "Douyin Archiving Setup - @小洛熙妈妈"
echo "================================================"
echo ""

# Create necessary directories
echo "[1/5] Creating directory structure..."
mkdir -p work/archiving/douyin-backup-$(date +%Y%m%d)/{videos,metadata,thumbnails,logs}
mkdir -p work/archiving/cookies

echo "✓ Directories created"
echo ""

# Check if Docker is installed
echo "[2/5] Checking Docker installation..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker not found. Installing..."
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Please install Docker Desktop from: https://www.docker.com/products/docker-desktop/"
        exit 1
    else
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    fi
else
    echo "✓ Docker found: $(docker --version)"
fi
echo ""

# Pull Douyin API Docker image
echo "[3/5] Pulling Douyin_TikTok_Download_API Docker image..."
docker pull evil0ctal/douyin_tiktok_download_api:latest
echo "✓ Docker image pulled"
echo ""

# Create docker-compose configuration
echo "[4/5] Creating docker-compose.yml..."
cat > work/archiving/docker-compose.yml << 'EOF'
version: '3.8'

services:
  douyin-api:
    image: evil0ctal/douyin_tiktok_download_api:latest
    container_name: douyin_archiving_api
    ports:
      - "8000:80"
    volumes:
      - ./cookies:/app/crawlers/douyin/web/
      - ./douyin-backup-$(date +%Y%m%d):/app/downloads
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
EOF

echo "✓ docker-compose.yml created"
echo ""

# Instructions for cookie extraction
echo "[5/5] Cookie extraction required..."
echo ""
echo "================================================"
echo "MANUAL STEP REQUIRED - Cookie Extraction"
echo "================================================"
echo ""
echo "You need to extract Douyin cookies from your browser:"
echo ""
echo "1. Open browser (Chrome/Firefox/Safari)"
echo "2. Go to: https://www.douyin.com"
echo "3. Log in to your Douyin account"
echo "4. Open Developer Tools (F12 or Cmd+Option+I)"
echo "5. Go to: Application → Cookies → https://www.douyin.com"
echo "6. Find and copy these cookie values:"
echo "   - ttwid"
echo "   - __ac_signature"
echo "   - sessionid"
echo "   - sid_guard"
echo ""
echo "7. Create file: work/archiving/cookies/config.yaml"
echo "8. Paste this template with your cookie values:"
echo ""
cat << 'COOKIETEMPLATE'
headers:
  Cookie: |
    ttwid=YOUR_TTWID_VALUE;
    __ac_signature=YOUR_AC_SIGNATURE_VALUE;
    sessionid=YOUR_SESSIONID_VALUE;
    sid_guard=YOUR_SID_GUARD_VALUE;
COOKIETEMPLATE
echo ""
echo "================================================"
echo ""
echo "After creating cookies/config.yaml, run:"
echo "  cd work/archiving"
echo "  docker-compose up -d"
echo "  python3 archive-douyin-account.py"
echo ""
echo "Setup complete! Waiting for cookies..."
