#!/bin/bash
# Gemini 2.5 Flash Video Analysis Setup
# Generated by CEO Agent - Phase 1.5 (FINAL)

set -e

echo "================================================"
echo "Gemini 2.5 Flash Video Analysis Setup"
echo "================================================"
echo ""

# Install Google Generative AI SDK
echo "[1/2] Installing Google Generative AI Python SDK..."
pip3 install --upgrade google-generativeai
echo "✓ SDK installed"
echo ""

# Check for API key
echo "[2/2] Checking for API key..."
if [ -z "$GOOGLE_API_KEY" ]; then
    echo "⚠ GOOGLE_API_KEY not set"
    echo ""
    echo "================================================"
    echo "ACTION REQUIRED: Get Google API Key"
    echo "================================================"
    echo ""
    echo "1. Go to: https://aistudio.google.com/apikey"
    echo "2. Click 'Create API Key'"
    echo "3. Copy the key"
    echo "4. Set environment variable:"
    echo ""
    echo "   export GOOGLE_API_KEY='your-key-here'"
    echo ""
    echo "Or add to your shell profile (~/.zshrc or ~/.bashrc):"
    echo ""
    echo "   echo 'export GOOGLE_API_KEY=\"your-key-here\"' >> ~/.zshrc"
    echo "   source ~/.zshrc"
    echo ""
else
    echo "✓ GOOGLE_API_KEY is set"
fi

echo ""
echo "================================================"
echo "Setup Complete!"
echo "================================================"
echo ""
echo "To analyze videos, run:"
echo "  python3 work/intelligence/video-analysis/analyze-videos-gemini.py"
echo ""
echo "This will:"
echo "  - Find all videos in media/ directory"
echo "  - Upload each to Gemini 2.5 Flash"
echo "  - Generate comprehensive analysis"
echo "  - Create individual + master reports"
echo ""
echo "Estimated:"
echo "  - Processing time: ~2-3 minutes per video"
echo "  - Cost: ~\$0.02 per video (~\$0.40 for 20 videos)"
echo ""
