#!/bin/bash
# Video Analysis Pipeline Setup
# Generated by CEO Agent - Phase 1.5 Video Analyst

set -e  # Exit on error

echo "================================================"
echo "Video Analysis Pipeline Setup"
echo "================================================"
echo ""

# Check system
echo "[1/6] Checking system..."
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "✓ macOS detected"
    PACKAGE_MANAGER="brew"
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "✓ Linux detected"
    PACKAGE_MANAGER="apt"
else
    echo "⚠ Unsupported OS: $OSTYPE"
    exit 1
fi
echo ""

# Install ffmpeg
echo "[2/6] Installing ffmpeg..."
if command -v ffmpeg &> /dev/null; then
    echo "✓ ffmpeg already installed: $(ffmpeg -version | head -n1)"
else
    if [[ "$PACKAGE_MANAGER" == "brew" ]]; then
        brew install ffmpeg
    else
        sudo apt update && sudo apt install -y ffmpeg
    fi
    echo "✓ ffmpeg installed"
fi
echo ""

# Install Python dependencies
echo "[3/6] Installing Python dependencies..."
pip3 install --upgrade pip
pip3 install openai-whisper anthropic aiohttp
echo "✓ Python packages installed"
echo ""

# Create directory structure
echo "[4/6] Creating directory structure..."
mkdir -p work/intelligence/video-analysis/{frames,audio,metadata,transcripts,frame-analysis,reports}
echo "✓ Directories created"
echo ""

# Check for API keys
echo "[5/6] Checking API keys..."

if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo "⚠ ANTHROPIC_API_KEY not set"
    echo "  Please set: export ANTHROPIC_API_KEY='your-key-here'"
    echo "  Or create .env file with: ANTHROPIC_API_KEY=your-key-here"
    API_KEYS_MISSING=true
else
    echo "✓ ANTHROPIC_API_KEY found"
fi

echo ""

# Test ffmpeg
echo "[6/6] Testing ffmpeg installation..."
ffmpeg -version | head -n1
echo "✓ ffmpeg working"
echo ""

echo "================================================"
echo "Setup Complete!"
echo "================================================"
echo ""

if [ "$API_KEYS_MISSING" = true ]; then
    echo "⚠ ACTION REQUIRED: Set API keys before running pipeline"
    echo ""
    echo "Set ANTHROPIC_API_KEY:"
    echo "  export ANTHROPIC_API_KEY='your-anthropic-key'"
    echo ""
fi

echo "To run the video analysis pipeline:"
echo "  python3 work/intelligence/video-analysis/analyze-videos.py"
echo ""
echo "Estimated processing time: 4-6 hours for 20 videos"
echo "Estimated cost: ~\$25 (Whisper + Claude APIs)"
echo ""
