#!/bin/bash
# Gemini 2.5 Flash Video Analysis Setup
# Generated by CEO Agent - Phase 1.5 (FINAL)
# Revised: Uses uv for virtual environment management

set -e

echo "================================================"
echo "Gemini 2.5 Flash Video Analysis Setup"
echo "================================================"
echo ""

# Step 1: Check for uv, install if needed
echo "[1/3] Checking for uv..."
if ! command -v uv &> /dev/null; then
    echo "⚠ uv not found, installing..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    echo "✓ uv installed"
    echo ""
    echo "IMPORTANT: Please restart your shell or run:"
    echo "  source \$HOME/.cargo/env"
    echo ""
    echo "Then re-run this script."
    exit 0
else
    echo "✓ uv is installed"
fi
echo ""

# Step 2: Create virtual environment and install dependencies
echo "[2/3] Setting up virtual environment..."
VENV_DIR="work/intelligence/video-analysis/.venv"

if [ -d "$VENV_DIR" ]; then
    echo "  Virtual environment already exists at $VENV_DIR"
else
    echo "  Creating virtual environment with uv..."
    cd work/intelligence/video-analysis
    uv venv
    cd ../../..
    echo "✓ Virtual environment created at $VENV_DIR"
fi
echo ""

echo "  Installing google-generativeai..."
uv pip install --python "$VENV_DIR/bin/python" google-generativeai
echo "✓ Dependencies installed"
echo ""

# Step 3: Check for API key
echo "[3/3] Checking for API key..."
if [ -z "$GOOGLE_API_KEY" ]; then
    echo "⚠ GOOGLE_API_KEY not set"
    echo ""
    echo "================================================"
    echo "ACTION REQUIRED: Get Google API Key"
    echo "================================================"
    echo ""
    echo "1. Go to: https://aistudio.google.com/apikey"
    echo "2. Click 'Create API Key'"
    echo "3. Copy the key"
    echo "4. Set environment variable:"
    echo ""
    echo "   export GOOGLE_API_KEY='your-key-here'"
    echo ""
    echo "Or add to your shell profile (~/.zshrc or ~/.bashrc):"
    echo ""
    echo "   echo 'export GOOGLE_API_KEY=\"your-key-here\"' >> ~/.zshrc"
    echo "   source ~/.zshrc"
    echo ""
else
    echo "✓ GOOGLE_API_KEY is set"
fi

echo ""
echo "================================================"
echo "Setup Complete!"
echo "================================================"
echo ""
echo "To analyze videos, run:"
echo "  work/intelligence/video-analysis/.venv/bin/python work/intelligence/video-analysis/analyze-videos-gemini.py"
echo ""
echo "Or activate the virtual environment first:"
echo "  source work/intelligence/video-analysis/.venv/bin/activate"
echo "  python work/intelligence/video-analysis/analyze-videos-gemini.py"
echo ""
echo "This will:"
echo "  - Find all videos in media/ directory"
echo "  - Upload each to Gemini 2.5 Flash"
echo "  - Generate comprehensive analysis"
echo "  - Create individual + master reports"
echo ""
echo "Estimated:"
echo "  - Processing time: ~2-3 minutes per video"
echo "  - Cost: ~\$0.02 per video (~\$0.40 for 20 videos)"
echo ""
